import type { Metadata } from "next";
import "./globals.css";
import Header from "./Header";
import { GazeProvider } from "./GazeContext";
import { libre_franklin, chivo } from "@/font";


export const metadata: Metadata = {
  title: "ReadEasy AI",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={libre_franklin.variable + " " + chivo.variable}>
        <GazeProvider>
          <Header />
          {children}
        </GazeProvider>
      </body>
    </html>
  );
}
